### ISSUE TITLE
Too many notifications

### ISSUE THREAD

**Issue by clemensp** [nulogy/nu-pomodoro#7]
For whatever reason, nu-pomodoro gives you many notifications.
Also, the notifications are not auto-dismissed, so you have to close all of them manually.

Is there a way to get them to auto-dismiss?

**Comment by clemensp** [comment]
I think....  that... we get notifications for everyone's pomodoro timers.

So if Jack and I are each running a timer, I get notified when my timer ends, and when Jack's timer ends.

**Comment by jaysoo** [comment]
I think I know why, I forgot to remove listeners.
 
Gonna push a fix soon.

**Comment by jaysoo** [comment]
@clemensp So we will need to add another NotificationStore to capture this state logic. Let me know if you are interested in pairing or taking this.

**Comment by clemensp** [comment]
Sure, let's pair sometime.

---------------------------------------------------
Clemens Park
Nulogy Corporation
Email: clemensp@nulogy.com

This email is subject to the terms of Nulogy's Confidentiality policy,
which can be viewed at: http://www.nulogy.com/confidentiality/
---------------------------------------------------

**Comment by jaysoo** [comment]
@clemensp I fixed this last night. It was getting annoying.

Let's pair on something else.

**Comment by jaysoo** [comment]
Seems like it might still exist.
